version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    container_name: gateway
    restart: always
    ports:
      - '2000:2000'
    command: npm run start:dev gateway
    depends_on:
      - redis
    networks:
      - app-net
    volumes:
      - .:/app
      - ./proto/:/app/dist/proto
      - /app/node_modules
  user-management:
    build:
      context: .
      dockerfile: ./apps/user-management/Dockerfile
    container_name: user-management
    restart: always
    ports:
      - '3000:3000'
      - '50051:50051'
    command: npm run start:dev user-management
    depends_on:
      - mongo
    networks:
      - app-net
    volumes:
      - .:/app
      - ./proto/:/app/dist/proto
      - /app/node_modules
  messenger:
    build:
      context: .
      dockerfile: ./apps/messenger/Dockerfile
    container_name: messenger
    restart: always
    ports:
      - '4000:4000'
      - '50052:50051'
    command: npm run start:dev messenger
    depends_on:
      - mongo
    networks:
      - app-net
    volumes:
      - .:/app
      - ./proto/:/app/dist/proto
      - /app/node_modules
  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-net
    volumes:
      - redis-data:/data
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-net
volumes:
  mongo-data:
  redis-data:
networks:
  app-net:




# protoc generation command
# protoc --plugin=protoc-gen-ts_proto="$(npm root)\.bin\protoc-gen-ts_proto.cmd" --ts_proto_out=./libs\shared\src --ts_proto_opt=nestJs=true ./proto/*.proto