version: '3.8'

services:
  user-management:
    build:
      context: .
      dockerfile: ./apps/user-management/Dockerfile
    container_name: user-management
    restart: always
    ports:
      - '3000:3000'
    command: npm run start:dev user-management
    depends_on:
      - mongo
    networks:
      - app-net
    volumes:
      - .:/app
      - /app/node_modules
  messenger:
    build:
      context: .
      dockerfile: ./apps/messenger/Dockerfile
    container_name: messenger
    restart: always
    ports:
      - '4000:4000'
    command: npm run start:dev messenger
    depends_on:
      - mongo
    networks:
      - app-net
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-net
    volumes:
      - redis-data:/data
volumes:
  mongo-data:
  redis-data:
networks:
  app-net:
