version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: builder
    container_name: gateway
    command: npm run start:dev gateway
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    env_file:
      - ./apps/gateway/env/local.env
    restart: always
    ports:
      - '2000:2000'
    depends_on:
      - redis
      - kafka
      - user-management
      - messenger
    networks:
      - app-net

  user-management:
    build:
      context: .
      dockerfile: ./apps/user-management/Dockerfile
      target: builder
    container_name: user-management
    command: npm run start:dev user-management
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    env_file:
      - ./apps/user-management/env/local.env
    restart: always
    ports:
      - '50051:50051'
    depends_on:
      - mongo
      - redis
      - kafka
    networks:
      - app-net

  messenger:
    build:
      context: .
      dockerfile: ./apps/messenger/Dockerfile
      target: builder
    command: npm run start:dev messenger
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    container_name: messenger
    env_file:
      - ./apps/messenger/env/local.env
    restart: always
    ports:
      - '50052:50051'
    depends_on:
      - mongo
      - redis
      - kafka
    networks:
      - app-net

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-net
    volumes:
      - redis-data:/data

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "3500:2181"
    networks:
      - app-net

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:3500
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-net

volumes:
  mongo-data:
  redis-data:
  api_node_modules:

networks:
  app-net:





# protoc generation command
# protoc --plugin=protoc-gen-ts_proto="$(npm root)\.bin\protoc-gen-ts_proto.cmd" --ts_proto_out=./libs\shared\src --ts_proto_opt=nestJs=true ./proto/*.proto